import { Inter } from 'next/font/google'
import ReduxToolkitProvider, { PersistGateProvider } from '@/redux/reduxProvider';
import { Toaster } from "react-hot-toast";
import Header from '@/app/_components/home/header';
import "@/assets/css/_components/layout.css";
import Marque from '@/app/_components/home/news_slider'
import Cover from '@/app/_components/home/cover'
import Faq from '@/app/_components/home/faq'
import Feedback from '@/app/_components/home/feedback'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import Modal from '@/app/_components/home/modals/login'
import { IoMdFingerPrint } from 'react-icons/io';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <h1>Header</h1> */}
      <body className={inter.className}>
        <ReduxToolkitProvider>
          <PersistGateProvider>
            <NextTopLoader showSpinner={false} />

            {/* <Marque
          title="News"
          list={[
            'KV-Dienstvertretung durch arztpool24 ist nicht sozialversicherungspflichtig',
            'KV-Vertreter bei arztpool24, die rechtssichere Alternative zum Poolarzt',
          ]}
        /> */}
            <Toaster position="top-center" />
            {children}
            {/* <Cover /> */}
            {/* <Faq /> */}
            {/* <Feedback /> */}
            {/* <Footer /> */}
            <div className="fingerprint_div">
              <IoMdFingerPrint className="fingerprint-icon" />
            </div>
          </PersistGateProvider>
        </ReduxToolkitProvider>
      </body>
    </html>
  )
}